#!/usr/bin/env python3
"""Build platform adapters from core/OBSIDIAN_KB.md + per-platform header.md.

Single source of truth = core/OBSIDIAN_KB.md (body starting from "## Overview").
Each platform contributes only its own header (YAML frontmatter, H1, trigger hint).
This script concatenates header + body and writes the adapter file.

Usage:
    python build.py            # build all adapters
    python build.py --check    # exit non-zero if any adapter is out of sync

Outputs are written with UTF-8 (no BOM) and LF line endings.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CORE_FILE = ROOT / "core" / "OBSIDIAN_KB.md"
BODY_MARKER = "## Overview"

# (platform_dir_name, output_filename_relative_to_platform_dir)
TARGETS = [
    ("qoderwork", "SKILL.md"),
    ("claude-code", "CLAUDE.md"),
    ("codex", "AGENTS.md"),
    ("cursor", "obsidian-kb.mdc"),
]

GENERATED_BANNER = (
    "<!-- AUTO-GENERATED by build.py from core/OBSIDIAN_KB.md + "
    "platforms/{name}/header.md. DO NOT EDIT DIRECTLY. -->\n\n"
)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    # UTF-8 without BOM, LF line endings.
    path.write_bytes(content.replace("\r\n", "\n").encode("utf-8"))


def extract_body(core_text: str) -> str:
    """Return everything from the BODY_MARKER heading onward.

    Only matches the marker when it appears at the start of a line
    (i.e. as a real markdown heading), not inside a quoted reference.
    """
    needle = "\n" + BODY_MARKER + "\n"
    idx = core_text.find(needle)
    if idx == -1:
        # Also accept the marker as the very first line of the file.
        if core_text.startswith(BODY_MARKER + "\n"):
            return core_text
        raise SystemExit(
            f"core/OBSIDIAN_KB.md is missing the body marker heading '{BODY_MARKER}'. "
            "Add the heading or update build.py."
        )
    return core_text[idx + 1 :]  # drop the leading newline


def build_adapter(header: str, body: str, platform_name: str) -> str:
    banner = GENERATED_BANNER.format(name=platform_name)
    # If header has YAML frontmatter, put banner AFTER the closing ---.
    if header.startswith("---\n"):
        end = header.find("\n---\n", 4)
        if end != -1:
            split_at = end + len("\n---\n")
            return header[:split_at] + "\n" + banner + header[split_at:].lstrip("\n") + body
    return banner + header + body


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Obsidian KB platform adapters.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files match source; exit 1 if out of sync.",
    )
    args = parser.parse_args()

    core_text = read_text(CORE_FILE)
    body = extract_body(core_text)

    drift = []
    for platform_name, output_name in TARGETS:
        header_path = ROOT / "platforms" / platform_name / "header.md"
        output_path = ROOT / "platforms" / platform_name / output_name
        if not header_path.exists():
            raise SystemExit(f"Missing header: {header_path}")
        header = read_text(header_path)
        adapter = build_adapter(header, body, platform_name)

        if args.check:
            if not output_path.exists() or read_text(output_path) != adapter:
                drift.append(str(output_path.relative_to(ROOT)))
            continue

        write_text(output_path, adapter)
        print(f"  wrote {output_path.relative_to(ROOT)}")

    if args.check:
        if drift:
            print("Out of sync:", file=sys.stderr)
            for f in drift:
                print(f"  - {f}", file=sys.stderr)
            print("\nRun: python build.py", file=sys.stderr)
            return 1
        print("All adapters are up to date.")
        return 0

    print(f"\nBuilt {len(TARGETS)} adapters from core/OBSIDIAN_KB.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
